# Generated by Django 5.2.6 on 2025-09-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
