# Generated by Django 5.2.6 on 2025-09-16 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_alter_employee_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("FT", "Full Time"),
                    ("PT", "Part Time"),
                    ("CT", "Contract"),
                    ("IN", "Intern"),
                ],
                default="FT",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="bonus",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Enter phone number in format: '+999999999'.",
                max_length=15,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emp_app.address",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="emp_app_emp_last_na_330504_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_id"], name="emp_app_emp_employe_f3d9b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["dept"], name="emp_app_emp_dept_id_5e97f6_idx"),
        ),
    ]
